import clsx from "clsx";
import Link from "@docusaurus/Link";
import useBaseUrl from "@docusaurus/useBaseUrl";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import Layout from "@theme/Layout";

import Heading from "@theme/Heading";
import styles from "./index.module.css";

const textContent = {
  customTests: `
  Write Pester tests that encode your organization's business and security policies.<br/><br/>
  <strong>Apply modern DevSecOps practices</strong> and continuously monitor critical aspects of your Microsoft cloud.
  `,
  whatIf: `
  Avoid creating loopholes in your conditional access policies and test to see the impact of a policy change before it is applied.<br/><br/>

  <strong>Identity is the new control plane!</strong> Create iron-clad tests to ensure your tenant's posture is always secure as your access policies evolve.
  `,
  maesterArchitecture: `
  Maester is built on top of Pester, the PowerShell test framework and <strong>super charges</strong> it with cloud capabilities and user friendly reports.<br/><br/>
  Quickly set up Maester in your environment by following the step-by-step guides we've built for you.<br/><br/>
  Bring the ease of writing tests in PowerShell to your Microsoft 365 tenant with Maester!<br/><br/>
  `,
  maesterReport: `
Get a quick snapshot of your tenant's security posture with the report generated by Maester.<br/><br/>
<strong>The interactive click-through</strong> report lets you drill down to the details of
each test.
<br/><br/>`,
  quickFix: `
Test details include direct links to the Microsoft admin portals.<br/><br/>
<strong>Jump straight</strong> into the conditional access policy that needs to be fixed or the group that needs to be reviewed.
<br/><br/>`,
  eidsca: `
Maester includes over 40+ out of the box tests from <a href="/docs/tests/eidsca/">Entra ID Security Config Analyzer (EIDSCA).</a><br/><br/>
EIDSCA is a part of the <strong>Microsoft Entra ID - Attack and Defense Playbook</strong> and is a collection of common attack scenarios on Microsoft Entra ID and how they can be mitigated.
<br/><br/>`,
  emailAlert: `
Set up email alerts to be delivered to your inbox with a
summary of the test results.
<br/><br/>
<strong>Get notified</strong> when a change is introduced in your Microsoft 365 tenant
that affects the security configuration.`,
  azureDevOps: `
Maester can be integrated with Azure DevOps Pipelines and scheduled to be run daily
and when changes are introduced in your Microsoft 365 tenant.
<br/><br/>
<strong>Follow the step-by-step guide</strong> in the Maester docs to set up
an automation account with Workload Identify Federation.`,
  gitHub: `
Integrate Maester with GitHub Actions to continuously monitor your tenant configuration.
<br/><br/>
<strong>Build an archive history</strong> of Maester test runs against your tenant with the native
workflow integration in Maester.
<br/><br/>
<strong>Use Workload Identify Federation</strong> for your automation account to connect to Microsoft Graph (no more secrets or credential rotation!).`,
};

const stats = [
  { value: "500K+", label: "PowerShell Gallery downloads" },
  { value: "120K+", label: "Tenants protected" },
  { value: "360+", label: "Built-in security tests" },
  { value: "5", label: "Compliance frameworks" },
];

const features = [
  {
    icon: "🔥",
    title: "Ready-made tests",
    body: "Hundreds of curated tests covering identity, access, devices and apps — ready to run on day one.",
  },
  {
    icon: "🛡️",
    title: "Confidently make changes",
    body: "Run regression tests before you change a Conditional Access policy. Catch loopholes before attackers do.",
  },
  {
    icon: "🛰️",
    title: "Continuous monitoring",
    body: "Schedule Maester in GitHub Actions, Azure DevOps or Azure Automation. Get alerts when posture drifts.",
  },
  {
    icon: "🧩",
    title: "Easy to customize",
    body: "Built on Pester and Microsoft Graph. Encode your own business and security policies as code.",
  },
  {
    icon: "🧭",
    title: "Configuration guidance",
    body: "Every test ships with remediation steps and direct links into the Microsoft admin portals.",
  },
  {
    icon: "🦅",
    title: "Compliance baselines",
    body: "EIDSCA, CISA SCuBA, CIS Microsoft 365 and ORCA — all wired into a single test framework.",
  },
];

const suites = [
  {
    emoji: "🔥",
    title: "Maester",
    desc: "Best-practice tests curated by the Maester community.",
    count: "170+ tests",
    href: "/docs/tests/maester",
  },
  {
    emoji: "🛡️",
    title: "EIDSCA",
    desc: "Entra ID Security Config Analyzer baseline.",
    count: "60+ tests",
    href: "/docs/tests/eidsca",
  },
  {
    emoji: "🦅",
    title: "CISA SCuBA",
    desc: "US CISA Secure Cloud Business Applications baselines.",
    count: "70+ tests",
    href: "/docs/tests/cisa",
  },
  {
    emoji: "🌀",
    title: "CIS M365",
    desc: "CIS Microsoft 365 Foundations Benchmark v3.1.0.",
    count: "60+ tests",
    href: "/docs/tests/cis",
  },
  {
    emoji: "📨",
    title: "ORCA",
    desc: "Office 365 Recommended Configuration Analyzer.",
    count: "Exchange Online",
    href: "/docs/tests/orca",
  },
];

function Hero() {
  const { siteConfig } = useDocusaurusContext();
  const logoUrl = useBaseUrl("/img/maester.png");
  return (
    <header className={styles.hero}>
      <div className={styles.heroGlow} aria-hidden="true" />
      <div className="container">
        <div className={styles.heroInner}>
          <span className={styles.heroBadge}>
            <span className={styles.heroBadgeDot} aria-hidden="true" />
            Open source · Community driven
          </span>
          <div className={styles.heroLogoWrap}>
            <img className={styles.heroLogo} src={logoUrl} alt="Maester" />
          </div>
          <Heading as="h1" className={styles.heroTitle}>
            Test automation for your <em>Microsoft 365</em> security posture
          </Heading>
          <p className={styles.heroSubtitle}>
            {siteConfig.tagline} — Maester turns Microsoft security best
            practices into runnable tests so you can make changes with
            confidence and prove compliance over time.
          </p>
          <div className={styles.heroButtons}>
            <Link className={styles.btnPrimary} to="/docs/installation">
              Get Started →
            </Link>
            <Link
              className={styles.btnGhost}
              to="https://github.com/maester365/maester"
            >
              Star on GitHub
            </Link>
          </div>
        </div>
        <div className={styles.heroShowcase}>
          <div className={styles.heroShowcaseFrame}>
            <img
              className={styles.heroShowcaseMedia}
              src={useBaseUrl("/img/maester-demo.gif")}
              alt="Maester running in a terminal and producing an interactive HTML report"
              loading="lazy"
            />
          </div>
        </div>
      </div>
    </header>
  );
}

function Stats() {
  return (
    <section className={styles.statsSection}>
      <div className="container">
        <div className={styles.stats}>
          {stats.map((s) => (
            <div key={s.label} className={styles.statItem}>
              <span className={styles.statValue}>{s.value}</span>
              <span className={styles.statLabel}>{s.label}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Features() {
  return (
    <section className={clsx(styles.section, styles.sectionAtmosphere)}>
      <div className="container">
        <div className={styles.sectionHeader}>
          <span className={styles.eyebrow}>Why Maester</span>
          <Heading as="h2" className={styles.sectionTitle}>
            Security as code, for the Microsoft cloud
          </Heading>
          <p className={styles.sectionLede}>
            One framework, hundreds of tests, every change validated. Maester
            is how modern teams keep Microsoft 365 secure as it evolves.
          </p>
        </div>
        <div className={styles.featureGrid}>
          {features.map((f) => (
            <article key={f.title} className={styles.featureCard}>
              <div className={styles.featureIcon} aria-hidden="true">
                {f.icon}
              </div>
              <h3 className={styles.featureTitle}>{f.title}</h3>
              <p className={styles.featureBody}>{f.body}</p>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}

function Suites() {
  return (
    <section className={styles.section}>
      <div className="container">
        <div className={styles.sectionHeader}>
          <span className={styles.eyebrow}>Test suites</span>
          <Heading as="h2" className={styles.sectionTitle}>
            Five baselines, one report
          </Heading>
          <p className={styles.sectionLede}>
            Run the suites you care about — community best practices and the
            major Microsoft 365 compliance baselines, all in one place.
          </p>
        </div>
        <div className={styles.suitesGrid}>
          {suites.map((s) => (
            <Link key={s.title} className={styles.suiteCard} to={s.href}>
              <span className={styles.suiteEmoji} aria-hidden="true">
                {s.emoji}
              </span>
              <h3 className={styles.suiteTitle}>{s.title}</h3>
              <p className={styles.suiteDesc}>{s.desc}</p>
              <span className={styles.suiteCount}>{s.count}</span>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}

function CtaBand() {
  return (
    <section>
      <div className="container">
        <div className={styles.ctaBand}>
          <Heading as="h2" className={styles.ctaTitle}>
            Run your first Maester test in under a minute
          </Heading>
          <p className={styles.ctaSubtitle}>
            Install the PowerShell module, connect to Microsoft Graph and get
            an interactive HTML report of your tenant's posture.
          </p>
          <div className={styles.heroButtons}>
            <Link className={styles.btnPrimary} to="/docs/installation">
              Get Started →
            </Link>
            <Link
              className={styles.btnGhost}
              to="https://github.com/maester365/maester"
            >
              View on GitHub
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ---------- Existing product story sections (kept) ---------- */

export function Section({
  element = "section",
  children,
  className,
  background = "light",
}) {
  const El = element;
  return (
    <El
      className={
        className
          ? `Section ${className} ${background}`
          : `Section ${background}`
      }
    >
      {children}
    </El>
  );
}

function Heading2({ text }) {
  return <h2 className="Heading">{text}</h2>;
}

function TextColumn({ title, text, moreContent }) {
  return (
    <div className="RightText">
      <Heading2 text={title} />
      <div dangerouslySetInnerHTML={{ __html: text }} />
      {moreContent}
    </div>
  );
}

function TwoColumns({ columnOne, columnTwo, reverse }) {
  return (
    <div className={`TwoColumns ${reverse ? "reverse" : ""}`}>
      <div className={`column first ${reverse ? "right" : "left"}`}>
        {columnOne}
      </div>
      <div className={`column last ${reverse ? "left" : "right"}`}>
        {columnTwo}
      </div>
    </div>
  );
}

function CustomTests() {
  return (
    <Section className="CrossPlatform" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn
            title="Security as Code (SaC)"
            text={textContent.customTests}
          />
        }
        columnTwo={
          <img
            className="FeatureImageLeft"
            alt="Code snippet for a custom test"
            src="img/home/custom-test.png"
          />
        }
      />
    </Section>
  );
}

function WhatIf() {
  return (
    <Section className="CrossPlatform">
      <TwoColumns
        columnOne={
          <TextColumn
            title="Conditional Access What-If"
            text={textContent.whatIf}
          />
        }
        columnTwo={
          <img
            className="FeatureImageRight"
            alt="Code sample of a what if test"
            src="img/home/conditional-access-policywhat-if-test.png"
          />
        }
      />
    </Section>
  );
}

function MaesterArchitecture() {
  return (
    <Section className="CrossPlatform" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn
            title="Maester Test Framework"
            text={textContent.maesterArchitecture}
          />
        }
        columnTwo={
          <img
            className="FeatureImageLeft"
            alt="Architecture diagram of Maester test framework"
            src="img/home/maester-architecture.png"
          />
        }
      />
    </Section>
  );
}

function MaesterReport() {
  return (
    <Section className="CrossPlatform">
      <TwoColumns
        columnOne={
          <TextColumn
            title="🔥 Maester Test Reports"
            text={textContent.maesterReport}
          />
        }
        columnTwo={
          <img
            className="FeatureImageRight"
            alt="Maester summary report"
            src="img/home/maester-report.png"
          />
        }
      />
    </Section>
  );
}

function GitHubSection() {
  return (
    <Section className="CrossPlatform LeftImage" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn title="Maester ❤️ GitHub" text={textContent.gitHub} />
        }
        columnTwo={
          <img
            className="FeatureImageLeft"
            alt="GitHub reports"
            src="img/home/github-maester-report.png"
          />
        }
      />
    </Section>
  );
}

function AzureDevOps() {
  return (
    <Section className="CrossPlatform">
      <TwoColumns
        columnOne={
          <TextColumn
            title="Maester 💛 Azure DevOps"
            text={textContent.azureDevOps}
          />
        }
        columnTwo={
          <img
            className="FeatureImageRight"
            alt="Azure DevOps Screenshot"
            src="img/home/azure-devops-maester-report.png"
          />
        }
      />
    </Section>
  );
}

function EmailAlert() {
  return (
    <Section className="CrossPlatform" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn title="Email Alerts" text={textContent.emailAlert} />
        }
        columnTwo={
          <img
            className="FeatureImageLeft"
            alt="Outlook email alerts"
            src="img/home/email-alert-test-results.png"
          />
        }
      />
    </Section>
  );
}

function Eidsca() {
  return (
    <Section className="CrossPlatform">
      <TwoColumns
        columnOne={
          <TextColumn title="40+ EIDSCA Tests" text={textContent.eidsca} />
        }
        columnTwo={
          <img
            className="FeatureImageRight"
            alt="Screenshot of an EIDSCA test result"
            src="img/home/maester-report-eidsca.png"
          />
        }
      />
    </Section>
  );
}

function QuickRemediation() {
  return (
    <Section className="CrossPlatform" background="tint">
      <TwoColumns
        reverse
        columnOne={
          <TextColumn title="Quick remediation" text={textContent.quickFix} />
        }
        columnTwo={
          <img
            alt="Screenshot of an EIDSCA test result"
            src="img/home/maester-report-detail.png"
          />
        }
      />
    </Section>
  );
}

export default function Home() {
  const { siteConfig } = useDocusaurusContext();
  return (
    <Layout
      title={siteConfig.title}
      description="Maester is the open source test automation framework for your Microsoft 365 security posture."
      wrapperClassName="home-page"
    >
      <div className={styles.home}>
        <Hero />
        <Stats />
        <Features />
        <Suites />
        <CtaBand />
      </div>
      <main className={styles.homeDark}>
        <CustomTests />
        <WhatIf />
        <MaesterArchitecture />
        <MaesterReport />
        <QuickRemediation />
        <Eidsca />
        <GitHubSection />
        <AzureDevOps />
        <EmailAlert />
      </main>
    </Layout>
  );
}
