function Test-MtCheckEidscaAM02 {
    <#
    .SYNOPSIS
    Checks if Authentication Method - Microsoft Authenticator - Allow use of Microsoft Authenticator OTP is 'false'

    .DESCRIPTION
    Defines if users can use the OTP code generated by the Authenticator App.

    Reads the tenant value of
    https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfigurations('MicrosoftAuthenticator')
    .isSoftwareOathEnabled with Test-MtEidscaAM02
    and passes when it -eq 'false'.
    #>
    [MaesterTest(
        Id = 'EIDSCA.AM02',
        Title = 'Authentication Method - Microsoft Authenticator - Allow use of Microsoft Authenticator OTP.',
        Severity = 'Medium',
        Category = 'EIDSCA',
        Product = 'Entra ID',
        Service = 'Graph',
        Author = 'Cloud-Architekt'
    )]
    [CmdletBinding()]
    [OutputType([bool])]
    param()

    $EnabledAuthMethods = (Get-MtAuthenticationMethodPolicyConfig -State Enabled).Id
    if ( $EnabledAuthMethods -notcontains 'MicrosoftAuthenticator' ) {
        Add-MtTestResultDetail -SkippedBecause 'Custom' -SkippedCustomReason 'Authentication method of Microsoft Authenticator is not enabled.'
        return $null
    }

    $tenantValue = Test-MtEidscaAM02
    return ($tenantValue -eq 'false')
}
