#
# Module manifest for module 'Maester'
#
# Generated by: Maester
#
# Generated on: 04/16/2024
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'Maester.psm1'

    # Version number of this module.
    ModuleVersion        = '3.0.0'

    # Supported PSEditions
    CompatiblePSEditions = 'Core'

    # ID used to uniquely identify this module
    GUID                 = '502a7fe7-b1ae-4bf5-98db-00831b14ed6f'

    # Author of this module
    Author               = 'Maester Team'

    # Company or vendor of this module
    CompanyName          = 'Maester Team'

    # Copyright statement for this module
    Copyright            = 'Maester Team. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'Maester is an automation framework to assess and monitor your Microsoft 365 security configuration.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '7.4'


    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules      = @(
        @{ModuleName = 'Microsoft.Graph.Authentication'; GUID = '883916f2-9184-46ee-b1f8-b6a2fb784cee'; ModuleVersion = '2.27.0'; }
        @{ModuleName = 'Pester'; GUID = 'a699dea5-2c73-4616-a270-1f7abb777e71'; ModuleVersion = '0.0.0'; }
    )
    <#
    Pester is declared above, but the minimum required version (5.5.0) is not pinned in this manifest due to
    potential conflicts with the version of Pester that is pre-installed with Windows. See
    <https://pester.dev/docs/introduction/installation/#windows>. Pester will be updated if necessary by
    Install-MaesterTests.
    #>

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess     = @()

    # The engine: the [MaesterTest] and [MaesterParameter] attribute types and the scheduling core.
    # Built from src/Maester.Engine by build/Build-MaesterEngine.ps1. Its cmdlets are not exported.
    NestedModules        = @('lib/Maester.Engine.dll')

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess     = @('Maester.Format.ps1xml')

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        'Add-MtMaesterAppFederatedCredential',
        'Add-MtTestResultDetail',
        'Clear-MtADCache',
        'Clear-MtDnsCache',
        'Clear-MtExoCache',
        'Clear-MtGraphCache',
        'Compare-MtJsonObject',
        'Compare-MtTestResult',
        'Connect-Maester',
        'Connect-MtGitHub',
        'Convert-MtResultsToFlatObject',
        'ConvertFrom-MailAuthenticationRecordDkim',
        'ConvertFrom-MailAuthenticationRecordDmarc',
        'ConvertFrom-MailAuthenticationRecordMx',
        'ConvertFrom-MailAuthenticationRecordSpf',
        'Disconnect-Maester',
        'Disconnect-MtGitHub',
        'Get-MailAuthenticationRecord',
        'Get-MtADDacls',
        'Get-MtADDomainState',
        'Get-MtADGpoState',
        'Get-MtAdminPortalUrl',
        'Get-MtAuthenticationMethodPolicyConfig',
        'Get-MtAzureManagementGroup',
        'Get-MtConditionalAccessPolicy',
        'Get-MtExo',
        'Get-MtExoThreatPolicyMalware',
        'Get-MtGraphScope',
        'Get-MtGroupMember',
        'Get-MtHtmlReport',
        'Get-MtLicenseInformation',
        'Get-MtMaesterApp',
        'Get-MtRegistrableDomain',
        'Get-MtRole',
        'Get-MtRoleMember',
        'Get-MtSafeMarkdown',
        'Get-MtSession',
        'Get-MtSetting',
        'Get-MtSpo',
        'Get-MtTenantContext',
        'Get-MtTest',
        'Get-MtTestInventory',
        'Get-MtUser',
        'Get-MtUserAuthenticationMethod',
        'Get-MtUserAuthenticationMethodInfoByType',
        'Import-MtMaesterResult',
        'Install-MaesterTests',
        'Invoke-Maester',
        'Invoke-MtAzureRequest',
        'Invoke-MtAzureResourceGraphRequest',
        'Invoke-MtGraphRequest',
        'Invoke-MtGraphSecurityQuery',
        'Invoke-MtTest',
        'Merge-MtMaesterResult',
        'New-MtMaesterApp',
        'New-MtTest',
        'Resolve-SPFRecord',
        'Send-MtMail',
        'Send-MtTeamsMessage',
        'Test-MtCaLicenseUtilization',
        'Test-MtCaMfaForRiskySignIn',
        'Test-MtCaRequirePasswordChangeForHighUserRisk',
        'Test-MtCaWIFBlockLegacyAuthentication',
        'Test-MtCisaDmarcReport',
        'Test-MtCisGitHubIssueDeletionLimited',
        'Test-MtCisGitHubRepositoryDeletionLimited',
        'Test-MtConditionalAccessWhatIf',
        'Test-MtConnection',
        'Test-MtEidscaControl',
        'Test-MtEntraIDConnectSsso',
        'Test-MtExoDelicensingResiliency',
        'Test-MtExoMoeraMailActivity',
        'Test-MtExoRejectDirectSend',
        'Test-MtPimAlertsExists',
        'Test-MtTeamsRestrictParticipantGiveRequestControl',
        'Test-ORCA100',
        'Test-ORCA101',
        'Test-ORCA102',
        'Test-ORCA103',
        'Test-ORCA104',
        'Test-ORCA105',
        'Test-ORCA106',
        'Test-ORCA107',
        'Test-ORCA108',
        'Test-ORCA108_1',
        'Test-ORCA109',
        'Test-ORCA110',
        'Test-ORCA111',
        'Test-ORCA112',
        'Test-ORCA113',
        'Test-ORCA114',
        'Test-ORCA115',
        'Test-ORCA116',
        'Test-ORCA118_1',
        'Test-ORCA118_2',
        'Test-ORCA118_3',
        'Test-ORCA118_4',
        'Test-ORCA119',
        'Test-ORCA120_malware',
        'Test-ORCA120_phish',
        'Test-ORCA120_spam',
        'Test-ORCA121',
        'Test-ORCA123',
        'Test-ORCA124',
        'Test-ORCA139',
        'Test-ORCA140',
        'Test-ORCA141',
        'Test-ORCA142',
        'Test-ORCA143',
        'Test-ORCA156',
        'Test-ORCA158',
        'Test-ORCA179',
        'Test-ORCA180',
        'Test-ORCA189',
        'Test-ORCA189_2',
        'Test-ORCA205',
        'Test-ORCA220',
        'Test-ORCA221',
        'Test-ORCA222',
        'Test-ORCA223',
        'Test-ORCA224',
        'Test-ORCA225',
        'Test-ORCA226',
        'Test-ORCA227',
        'Test-ORCA228',
        'Test-ORCA229',
        'Test-ORCA230',
        'Test-ORCA231',
        'Test-ORCA232',
        'Test-ORCA233',
        'Test-ORCA233_1',
        'Test-ORCA234',
        'Test-ORCA235',
        'Test-ORCA236',
        'Test-ORCA237',
        'Test-ORCA238',
        'Test-ORCA239',
        'Test-ORCA240',
        'Test-ORCA241',
        'Test-ORCA242',
        'Test-ORCA243',
        'Test-ORCA244',
        'Update-MaesterTests',
        'Update-MtMaesterApp'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    # VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @(
        'Invoke-MtMaester',
        'Connect-MtGraph', 'Connect-MtMaester',
        'Disconnect-MtGraph', 'Disconnect-MtMaester',
        'Get-MtMaesterConfigGlobalSetting'
    )

    # List of all modules packaged with this module
    # ModuleList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = 'Microsoft', '365', 'Cloud', 'Test', 'Pester', 'Entra', 'AzureAD', 'Automation', 'Regression', 'DevOps', 'EntraID'

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/maester365/maester/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://maester.dev'

            # A URL to an icon representing this module.
            IconUri      = 'https://maester.dev/img/logo.svg'

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/maester365/maester/releases'

            # Prerelease string of this module
            # Prerelease = ''

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI          = 'https://maester.dev/docs/commands/'

}
