# Generated by ./build/orca/Update-OrcaTests.ps1 from powershell/internal/orca/check-ORCA118_1.ps1. Do not edit.

function Test-ORCA118_1 {
    <#
    .SYNOPSIS
    Domains are not being allow listed in an unsafe manner in Anti-Spam Policies.

    .DESCRIPTION
    Runs the ORCA check ORCA118_1 (https://github.com/cammurray/orca) against the Exchange Online configuration.

    .LINK
    https://maester.dev/docs/tests/ORCA.118.1
    #>
    [MaesterTest(
        Id = 'ORCA.118.1',
        Title = 'Domains are not being allow listed in an unsafe manner in Anti-Spam Policies.',
        Severity = 'High',
        Category = 'ORCA',
        Tag = 'EXO',
        Service = 'ExchangeOnline',
        Author = 'thomas-s-schmidt'
    )]
    [CmdletBinding()]
    [OutputType([bool])]
    param()

    $Collection = Get-MtOrcaCollection
    $obj = New-Object -TypeName ORCA118_1
    try { # Handle "SkipInReport" which has a continue statement that makes this function exit unexpectedly
        $obj.Run($Collection)
    } catch {
        Write-OrcaError -TestId "ORCA118_1" -ErrorRecord $_ -AdditionalContext "Running ORCA118_1 test"
        throw
    } finally {
        if ($obj.SkipInReport) {
            Add-MtTestResultDetail -SkippedBecause 'Custom' -SkippedCustomReason 'The statement "SkipInReport" was specified by ORCA.'
        }
    }

    if ($obj.CheckFailed) {
        Add-MtTestResultDetail -SkippedBecause 'Custom' -SkippedCustomReason $obj.CheckFailureReason
        return $null
    } elseif (-not $obj.Completed) {
        Add-MtTestResultDetail -SkippedBecause 'Custom' -SkippedCustomReason 'Possibly missing license for specific feature.'
        return $null
    }

    $testResult = ($obj.ResultStandard -eq "Pass" -or $obj.ResultStandard -eq "Informational")

    if ($testResult) {
        $resultMarkdown = "Well done! Domains are not being allow listed in an unsafe manner in Anti-Spam Policies.`n`n%ResultDetail%"
    } else {
        $resultMarkdown = "The configured settings are not set as recommended.`n`n%ResultDetail%"
    }

    # Return early if we don't need to expand the results
    if (-not $obj.ExpandResults) {
        Add-MtTestResultDetail -Result $resultMarkdown.TrimEnd("%ResultDetail%")
        return $testResult
    }

    $passResult = "`u{2705} Pass"
    $failResult = "`u{274C} Fail"
    $skipResult = "`u{1F5C4} Skip"
    $showObject = "" + $obj.CheckType -eq "ObjectPropertyValue"

    $resultDetail = "`n`n"
    if ($showObject) { $resultDetail += "|$($obj.ObjectType)" }
    $resultDetail += "|$($obj.ItemName)|$($obj.DataType)|Result|`n"

    if ($showObject) { $resultDetail += "|-" }
    $resultDetail += "|-|-|-|`n"

    foreach ($result in $obj.Config) {
        if ($result.ResultStandard -eq "Pass") {
            $objResult = $passResult
        } elseif ($result.ResultStandard -eq "Informational") {
            $objResult = $skipResult
        } else {
            $objResult = $failResult
        }
        if ($showObject) { $resultDetail += "|$($result.Object)" }
        $resultDetail += "|$($result.ConfigItem)|$($result.ConfigData)|$objResult|`n"
    }
    $resultMarkdown = $resultMarkdown -replace "%ResultDetail%", $resultDetail

    Add-MtTestResultDetail -Result $resultMarkdown

    return $testResult
}
