// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  siteSidebar: [
    "intro",
    "writing-tests",
    {
      type: "category",
      label: "Monitoring with Maester",
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "monitoring" }],
    },
    "contributing",
    "faq",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Test Reference",
      collapsed: false,
      items: [
        "tests/overview",
        {
          type: "category",
          label: "Maester",
          collapsed: false,
          collapsible: false,
          items: [{ type: "autogenerated", dirName: "tests/maester" }],
        },
        {
          type: "category",
          label: "Entra ID SCA",
          collapsed: false,
          collapsible: false,
          items: [{ type: "autogenerated", dirName: "tests/eidsca" }],
        },
      ],
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Command Reference",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "commands" }],
    },
  ],
};

export default sidebars;
