// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  siteSidebar: [
    {
      type: "html",
      value: '<span class="sidebar-section">Get Started</span>'
    },
    "intro",
    "installation",
    {
      type: "category",
      label: "🔗 Connect-Maester",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "connect-maester" }]
    },
    {
      type: "html",
      value: '<span class="sidebar-section">Use Maester</span>'
    },
    {
      type: "category",
      label: "⚙️ Configure Maester",
      collapsed: true,
      collapsible: true,
      link: {type: 'doc', id: 'configuration/overview'},
      items: [{ type: "autogenerated", dirName: "configuration" }]
    },
    "updating-tests",
    "ca-what-if",
    "export-results",
    {
      type: "html",
      value: '<span class="sidebar-section">Automate &amp; Monitor</span>'
    },
    {
      type: "category",
      label: "👁️‍🗨️ Monitoring with Maester",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "monitoring" }]
    },
    {
      type: "category",
      label: "📮 Maester Alerts",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "alerts" }]
    },
    {
      type: "html",
      value: '<span class="sidebar-section">Advanced</span>'
    },
    {
      type: "category",
      label: "🏢 Multi-Tenant",
      collapsed: true,
      collapsible: true,
      link: {type: 'doc', id: 'multi-tenant/overview'},
      items: [{ type: "autogenerated", dirName: "multi-tenant" }]
    },
    {
      type: "category",
      label: "🛠️ Writing custom tests",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "writing-tests" }]
    },
    {
      type: "html",
      value: '<span class="sidebar-section">Resources</span>'
    },
    "watch",
    "contributing",
    "faq",
    {
      type: "html",
      value: '<span class="sidebar-divider" />'
    },
    {
      type: "category",
      collapsed: false,
      label: "Tests Overview",
      link: {type: 'doc', id: 'tests/maester/overview'},
      items: [
        {
          type: "category",
          label: "🔥 Maester",
          link: {type: 'doc', id: 'tests/maester/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/maester" }]
        },
        {
          type: "category",
          label: "🛡️ Entra ID SCA",
          link: {type: 'doc', id: 'tests/eidsca/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/eidsca" }]
        },
        {
          type: "category",
          label: "🦅 CISA",
          link: {type: 'doc', id: 'tests/cisa/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/cisa" }]
        },
        {
          type: "category",
          label: "🛡️ Defender for Endpoint",
          link: {type: 'doc', id: 'tests/defender/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/defender" }]
        },
        'tests/cis/overview',
        "tests/tags/overview"
      ]
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />'
    },
    {
      type: "category",
      label: "Command Reference",
      collapsed: true,
      //className: "powershell",
      items: [{ type: "autogenerated", dirName: "commands" }]
    }
  ]
};

export default sidebars;
