#
# Module manifest for module 'Maester'
#
# Generated by: Microsoft Identity
#
# Generated on: 01/14/2024
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'Maester.psm1'

    # Version number of this module.
    ModuleVersion        = '0.0.11'

    # Supported PSEditions
    CompatiblePSEditions = 'Core', 'Desktop'

    # ID used to uniquely identify this module
    GUID                 = '502a7fe7-b1ae-4bf5-98db-00831b14ed6f'

    # Author of this module
    Author               = 'Maester Team'

    # Company or vendor of this module
    CompanyName          = 'Maester.dev'

    # Copyright statement for this module
    Copyright            = 'Microsoft Corporation. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'This module will help you write tests and monitor your Microsoft 365 tenant configuration.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules      = @(@{ModuleName = 'Microsoft.Graph.Authentication'; GUID = '883916f2-9184-46ee-b1f8-b6a2fb784cee'; ModuleVersion = '2.2.0'; })

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules        = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = 'Clear-MtGraphCache', 'Get-MtConditionalAccessPolicies',
    'New-MtTestReport',
    'Invoke-MtGraphRequest', 'Test-MtAppManagementPolicyEnabled',
    'Test-MtCaAllAppsExists', 'Test-MtCaDeviceComplianceExists',
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = 'Clear-MtGraphCache', 'Get-MtConditionalAccessPolicies',
    'Invoke-MtGraphRequest', 'Test-MtAppManagementPolicyEnabled',
    'Test-MtCaAllAppsExists',
    'Test-MtCaApplicationEnforcedRestrictions',
    'Test-MtCaBlockLegacyExchangeActiveSyncAuthentication',
    'Test-MtCaBlockLegacyOtherAuthentication',
    'Test-MtCaBlockUnknownOrUnsupportedDevicePlatforms',
    'Test-MtCaDeviceComplianceAdminsExists',
    'Test-MtCaDeviceComplianceExists', 'Test-MtCaEmergencyAccessExists',
    'Test-MtCaEnforceNonPersistentBrowserSession',
    'Test-MtCaEnforceSignInFrequency', 'Test-MtCaMfaForAdminManagement',
    'Test-MtCaMfaForAdmins', 'Test-MtCaMfaForAllUsers',
    'Test-MtCaMfaForGuests', 'Test-MtCaMfaForRiskySignIns',
    'Test-MtCaRequirePasswordChangeForHighUserRisk',
    'Test-MtCaSecureSecurityInfoRegistration',
    'Test-MtConditionalAccessWhatIf'
    Tags = 'Maester', 'Microsoft', '365', 'Cloud', 'Test', 'Pester', 'Entra', 'AzureAD', 'Automation', 'Regression', 'DevOps'

    # A URL to the license for this module.
    LicenseUri = 'https://github.com/maester365/maester/blob/main/LICENSE'

    # A URL to the main website for this project.
    ProjectUri = 'https://github.com/maester365/maester'

    # A URL to an icon representing this module.
    # IconUri = ''

    # ReleaseNotes of this module
    # ReleaseNotes = ''

    # Prerelease string of this module
    # Prerelease = ''

    # Flag to indicate whether the module requires explicit user acceptance for install/update/save
    # RequireLicenseAcceptance = $false

    # External dependent modules of this module
    # ExternalModuleDependencies = @()

} # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

