# Regenerates the documentation for the "Command Reference" section of the site https://maester.dev
name: build-docs

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

concurrency:
  group: build-docs
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Generate maester-bot app token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.MAESTER_BOT_APP_ID }}
          private-key: ${{ secrets.MAESTER_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Update docs
        run: ./build/Update-CommandReference.ps1
        shell: pwsh

      - name: Create PR to update repo
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: Update maester.dev command reference
