name: build-validation-report
on:
  workflow_run:
    workflows: ["build-validation"] # runs after build-validation workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@d6b6b979a50e94f3ba9e88a5ebac47c9f381c7d3 # v3.0.0
        with:
          artifact: test-results-Windows
          name: Maester Test Results
          path: "*.xml"
          reporter: java-junit
          fail-on-error: true
