# Run pester tests
name: build-validation

on:
  workflow_dispatch:
  workflow_call:

  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  build-validation:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            pwshmodule:
              - 'powershell/**'
              - 'report/**'
              - 'tests/**'
              - '.github/workflows/build-validation.yaml'

      - name: Install PowerShell dependencies
        if: steps.filter.outputs.pwshmodule == 'true'
        shell: pwsh
        run: |
          Install-Module PSFramework -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber
          Install-Module PSModuleDevelopment -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber
          Install-Module Microsoft.Graph.Authentication -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber
          try {
            Install-Module Microsoft.PowerShell.PSResourceGet -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber -ErrorAction Stop
          }
          catch {
            Write-Warning "Unable to install Microsoft.PowerShell.PSResourceGet: $($_.Exception.Message)"
          }

      - name: Run Pester tests
        if: steps.filter.outputs.pwshmodule == 'true'
        shell: pwsh
        run: |
          ./powershell/tests/pester.ps1

      - name: Run Tests using Windows PowerShell
        if: runner.os == 'Windows' && steps.filter.outputs.pwshmodule == 'true'
        shell: powershell
        run: |
          # Reuse downloaded modules from pwsh
          $env:PSModulePath = ($env:PSModulePath).TrimEnd(';')+";$HOME\Documents\PowerShell\Modules"
          # Remove old test results
          Remove-Item -Path TestResults -Recurse -Force -ErrorAction SilentlyContinue
          # Run Pester tests on Windows PowerShell
          ./powershell/tests/pester.ps1

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: (success() || failure()) && steps.filter.outputs.pwshmodule == 'true' # run this step even if previous step failed and tests were run
        with:
          name: test-results-${{ runner.os }}
          path: TestResults/*.xml
