name: publish-module-preview

on:
  push:
    branches:
      - main
    paths:
      - "powershell/**"
      - "!powershell/Maester.psd1"
      - "report/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  checks: write
  actions: read
  pull-requests: write
  statuses: write

jobs:
  build-report:
    uses: ./.github/workflows/build-report.yaml

  create-preview-release:
    needs: build-report
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Download updated report template
        if: needs.build-report.outputs.report-updated == 'true'
        uses: actions/download-artifact@v4
        with:
          name: updated-report-template
          path: powershell/assets/

      - name: Package ./tests to PowerShell module
        id: package-tests
        shell: pwsh
        run: ./build/Copy-MaesterTestsToPSModule.ps1 -Force

      - name: Set module version
        id: moduleversion
        shell: pwsh
        run: ./.github/workflows/minor-version-update.ps1 -preview

      - name: Archive PowerShell build
        uses: actions/upload-artifact@v5
        with:
          name: maester-module
          path: |
            ${{ github.workspace }}/powershell

      - name: Update PowerShell Module to PowerShell Gallery
        id: publish-to-gallery
        shell: pwsh
        run: |
          Publish-Module -Path ${{ github.workspace }}/powershell -NuGetApiKey ${{ secrets.PS_GALLERY_KEY }}

      - name: Build PowerShell module for GitHub
        id: module-creation
        shell: pwsh
        run: |
          Compress-Archive -Path ${{ github.workspace }}/build/maester/* -DestinationPath ${{ github.workspace }}/maester.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "maester.zip"
          replacesArtifacts: true
          allowUpdates: true
          generateReleaseNotes: true
          makeLatest: false
          prerelease: true
          tag: ${{ steps.moduleversion.outputs.tag }}
          commit: ${{ github.sha }}
