name: publish-module-preview

on:
  push:
    branches:
      - main
    paths:
      - "powershell/**"
      - "!powershell/Maester.psd1"
      - "report/**"
  workflow_dispatch:

permissions: {}

jobs:
  build-report:
    uses: ./.github/workflows/build-maester-report-template.yaml
    permissions:
      contents: read
      actions: read

  create-preview-release:
    needs: build-report
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download updated report template
        if: needs.build-report.outputs.report-updated == 'true'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: updated-report-template
          path: powershell/assets/

      - name: Package ./tests to PowerShell module
        id: package-tests
        shell: pwsh
        run: ./build/Copy-MaesterTestsToPSModule.ps1 -Force

      - name: Set module version
        id: moduleversion
        shell: pwsh
        run: ./.github/workflows/minor-version-update.ps1 -preview

      - name: Archive PowerShell build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: maester-module
          path: |
            ${{ github.workspace }}/powershell

      - name: Update PowerShell Module to PowerShell Gallery
        id: publish-to-gallery
        shell: pwsh
        run: |
          # Copy to maester folder to avoid issues when publishing
          Copy-Item ${{ github.workspace }}/powershell -Recurse -Destination ${{ github.workspace }}/maester/ -Force
          Publish-Module -Path ${{ github.workspace }}/maester -NuGetApiKey ${{ secrets.PS_GALLERY_KEY }}

      - name: Build PowerShell module for GitHub
        id: module-creation
        shell: pwsh
        run: |
          Compress-Archive -Path ${{ github.workspace }}/maester/* -DestinationPath ${{ github.workspace }}/maester.zip

      - name: Create release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: "maester.zip"
          replacesArtifacts: true
          allowUpdates: true
          generateReleaseNotes: true
          makeLatest: false
          prerelease: true
          tag: ${{ steps.moduleversion.outputs.tag }}
          commit: ${{ github.sha }}
