name: update-module-docs

on:
  push:
    branches:
      - main
    paths:
      - "powershell/**"
      - "!powershell/Maester.psd1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-command-reference:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Update maester.dev powershell docs
        run: ./build/Update-CommandReference.ps1
        shell: pwsh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          title: Update maester.dev powershell docs
