name: update-module-docs

on:
  push:
    branches:
      - main
    paths:
      - "powershell/**"
      - "!powershell/Maester.psd1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: update-module-docs
  cancel-in-progress: false

jobs:
  update-command-reference:
    runs-on: windows-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Generate maester-bot app token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.MAESTER_BOT_APP_ID }}
          private-key: ${{ secrets.MAESTER_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Update maester.dev powershell docs
        run: ./build/Update-CommandReference.ps1
        shell: pwsh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: Update maester.dev powershell docs
