function Test-MtAdNonAutoReplicationConnectionCount {
    <#
    .SYNOPSIS
    Checks for non-auto-generated Active Directory replication connections.

    .DESCRIPTION
    Active Directory replication connections can be automatically generated by the
    Knowledge Consistency Checker (KCC) or manually created by administrators.
    Non-auto-generated (manual) connections may be necessary for specific scenarios
    but should be documented and reviewed regularly as they bypass automatic
    topology optimization.

    Security Best Practice:
    - Prefer auto-generated connections for standard replication topology
    - Manual connections should be documented with business justification
    - Regularly review manual connections to ensure they are still needed
    - Excessive manual connections may indicate topology issues

    .EXAMPLE
    Test-MtAdNonAutoReplicationConnectionCount

    Returns $true if replication connection data is accessible.

    .LINK
    https://maester.dev/docs/commands/Test-MtAdNonAutoReplicationConnectionCount
    #>
    [CmdletBinding()]
    [OutputType([bool])]
    param()

    $adState = Get-MtADDomainState

    if ($null -eq $adState) {
        Add-MtTestResultDetail -SkippedBecause NotConnectedActiveDirectory
        return $null
    }

    $replicationConnections = $adState.ReplicationConnections
    $totalConnections = ($replicationConnections | Measure-Object).Count
    $manualConnections = $replicationConnections | Where-Object { $_.AutoGenerated -eq $false }
    $manualCount = ($manualConnections | Measure-Object).Count

    $testResult = $true

    $result = "| Property | Value |`n"
    $result += "| --- | --- |`n"
    $result += "| Total Replication Connections | $totalConnections |`n"
    $result += "| Auto-Generated Connections | $($totalConnections - $manualCount) |`n"
    $result += "| Manual (Non-Auto) Connections | $manualCount |`n"

    if ($totalConnections -gt 0) {
        $percentage = [Math]::Round(($manualCount / $totalConnections) * 100, 2)
        $result += "| Manual Connection Percentage | $percentage% |`n"
    }

    $testResultMarkdown = "Active Directory replication connections have been analyzed. Manual connections bypass automatic topology optimization and should be documented.`n`n%TestResult%"
    $testResultMarkdown = $testResultMarkdown -replace "%TestResult%", $result

    Add-MtTestResultDetail -Result $testResultMarkdown

    return $testResult
}
